theme: hbp

canonifyURLs: false
cleanDestinationDir: true
copyright: Public Domain
defaultContentLanguage: en
metaDataFormat: yaml
noTimes: true
publishDir: public
relativeURLs: true
verbose: false
watch: true

disableKinds:
    - RSS
    - taxonomy
    - taxonomyTerm

languages:
    en:
        languageCode: en-us
        languageLang: en
        languageName: English
        weight: 0

####################################################################################################
baseURL: https://hbp.vercel.app/
title: HBP

params:
    resources:
        fingerprint: false
        inline: false

        css:
            - https://cdn.jsdelivr.net/npm/@u29dc/set@2.0.0/dist/main.min.css

    description: Lorem ipsum
    email: email@example.com
    license: https://creativecommons.org/publicdomain/zero/1.0
    src: https://github.com/u29dc/hbp
    username: #

    links:
        twitter: https://twitter.com/#
        github: https://github.com/#
