theme: hbp

canonifyURLs: false
cleanDestinationDir: true
copyright: Public Domain
defaultContentLanguage: en
metaDataFormat: yaml
noTimes: true
publishDir: public
relativeURLs: true
verbose: false
watch: true
disableKinds:
    - RSS
    - taxonomy
    - taxonomyTerm
minify:
    minifyOutput: true
    tdewolff:
        html:
            keepConditionalComments: false
            keepQuotes: true

languages:
    en:
        languageCode: en-us
        languageLang: en
        languageName: English
        weight: 0

####################################################################################################
baseURL: https://hbp.vercel.app/
title: HBP

params:
    resources:
        fingerprint: false
        inline: false

        # css:
        #     - src: https://cdn.jsdelivr.net/example.css

        # js:
        #     - src: https://cdn.jsdelivr.net/example.js
        #       sri: sha512-xxx

    description: Hugo Boilerplate Theme
    email: email@example.com
    license: https://creativecommons.org/publicdomain/zero/1.0
    src: https://github.com/u29dc/hbp
    username: #

    links:
        twitter: https://twitter.com/#
        github: https://github.com/#
