theme: hbp
# module:
#     imports:
#         - path: github.com/u29dc/hbp

canonifyURLs: false
cleanDestinationDir: true
copyright: Public Domain
defaultContentLanguage: en
metaDataFormat: yaml
noTimes: true
publishDir: public
relativeURLs: true
verbose: false
watch: true
disableKinds:
    - RSS
    - taxonomy
    - taxonomyTerm
minify:
    minifyOutput: true
    tdewolff:
        html:
            keepConditionalComments: false
            keepQuotes: true

languages:
    en:
        languageCode: en-us
        languageLang: en
        languageName: English
        weight: 0

####################################################################################################
baseURL: https://hbp.vercel.app/
title: HBP

params:
    resources:
        fingerprint: true
        inline: false

        css:
            - src: https://cdn.jsdelivr.net/npm/@u29dc/set@2.0.0/dist/main.min.css
              sri: sha512-Z+AGHZNUHSRgNUesBXbRDAJVSCrMkBYr9NdZABs/ESMLOVoWR9UW9E3tBScqq8CLEsg4oGoxHYHyAYn4mmRO3w==

        # js:
        #     - src: https://cdn.jsdelivr.net/example.js
        #       sri: sha512-xxx

    description: Hugo Boilerplate Theme
    email: x@example.com
    license: https://creativecommons.org/publicdomain/zero/1.0
    src: https://github.com/u29dc/hbp
    username: x

    links:
        twitter: https://twitter.com/x
        github: https://github.com/x
